### ISSUE TITLE
When editing a active subscription, the price is x10

### ISSUE THREAD

**Issue by mdlonline** [Adyen/adyen-magento-subscription#52]
When editing a active subscription ,and adding a product to it, after selecting the product checkbox it shows a price of 2150 instead of 21,50.
Adding the product works fine with the correct price, however.

**Comment by rikterbeek** [comment]
Hi mdlonline,

I do not have this. What version of magento are you using ? Do you have this as well if you create an order in the backend without an subscription ? (maybe it is not related to our extension)

Just to get the right steps:
1. Go into the subscription
2. Select "edit subscription"
3. Select "Add products"
4. Select the checkbox
5. Select a subscription from dropdown box and select "OK"
The label is now showing 2150 instead of 21,50 right ? 

Regards,
Rik
Adyen

**Comment by mdlonline** [comment]
You are right, i have it with normal products also. Thanks for helping out, issue can be closed
