### ISSUE TITLE
Subscriptions forget their website after saving.

### ISSUE THREAD

**Issue by sandermangel** [Adyen/adyen-magento-subscription#70]
When I add subscriptions to a bundled product and set the website they belong to I can save that on default but when I save it on a store level this data is forgotten and the subscription is added as default

![screenshot](http://i.imgur.com/nS1aiDd.png)

**Comment by rikterbeek** [comment]
HI @sandermangel,

By default bundle products don't allow adyen subscription. You can use the simple bundle solution from H&O https://github.com/ho-nl/magento1-Ho_SimpleBundle are you using this one ? if so how did you setup this on your end because on mine this is not occurring. 

Regards,
Rik
Adyen

**Comment by sandermangel** [comment]
@rikterbeek no. but please explain why I can make a subscription on a bundled product then?
It's not like it doesn't work at all, apparently it works 75%? Nowhere in the documentation is this mentioned.
Forcing a shop to work with https://github.com/ho-nl/magento1-Ho_SimpleBundle is not really an option is it?
We've built a shop now based on bundled products, I guess I have to rebuild it? Does this only work with simples then?

**Comment by rikterbeek** [comment]
Hi @sandermangel,

Great that you came by our office so we could solve this together! Now let's test this code and if some fixes are needed let's commit it against issue #71.

Regards,
Rik
Adyen
