### ISSUE TITLE
Activating subscription resets scheduled date

### ISSUE THREAD

**Issue by sandermangel** [Adyen/adyen-magento-subscription#82]
Do we have any idea why the following happens: https://github.com/Adyen/adyen-magento-subscription/blob/develop/app/code/community/Adyen/Subscription/Model/Subscription.php#L518

When activating a subscription the scheduled at date is reset to the current date triggering a direct order. Expected behavior would be to keep the normal scheduled_at date

**Comment by sandermangel** [comment]
Discussed with @paales, he indicated it's probably a development artifact, created https://github.com/Adyen/adyen-magento-subscription/pull/83 te remove.

**Comment by paales** [comment]
The initial commit: https://github.com/Adyen/adyen-magento-subscription/commit/73dcba5b1ad4cee33348225032665405be526a3a#diff-f7ce25ed158cc1a170ef6c1c7d6aa80cR335
Related: https://github.com/Adyen/adyen-magento-subscription/commit/595ddcc7b5f03baa4208969bffeaacd940d4faca,  https://github.com/Adyen/adyen-magento-subscription/commit/877a9f87390530e3ec03bfc86c0df32b31d75ade (Rename van het NextOrderAt > ScheduletAt)

Since this line is committed in the first commit, I think it can be safely removed.
